project:
  type: website
  title: "macro_sex"

website:
  navbar:
    left:
      - text: "Home"
        href: index.qmd
      - text: "Interactive Sex Recombination"
        href: interactive-sex-recombination.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
